site_name: Lidar Simulation
site_url: http://localhost:8000/
nav:
  - Simulation: "index.md"
  - Lidar: "lidar.md"
  - w2a<: about.md
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - extra
  - tables
  - fenced_code
